_wandb:
    value:
        cli_version: 0.21.0
        e:
            b0y5cpqgmohtk0k3wv9krtn9vkgcmiqn:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "220727341056"
                        used: "192795832320"
                email: 555prashantmishra@gmail.com
                executable: C:\Python31\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-9b25cad1-81b6-928b-d689-aae440111b31
                host: LAPTOP-LDPN3661
                memory:
                    total: "7887228928"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\prash\Downloads\ayna-ml-assignment\src\train.py
                python: CPython 3.10.9
                root: C:\Users\prash\Downloads\ayna-ml-assignment
                startedAt: "2025-08-05T05:22:07.308676Z"
                writerId: b0y5cpqgmohtk0k3wv9krtn9vkgcmiqn
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
            "4": 3.10.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
